source 'http://rubygems.org'
gem 'pg'
gem 'rails', '3.2.6'
gem 'rack'
gem 'devise'
gem 'devise-encryptable'
gem 'cancan'
gem 'cantango'
gem 'aws-s3', :require => 'aws/s3'
gem 'aws-sdk'
gem 'faker'
gem 'omniauth'
gem 'thinking-sphinx'
gem 'unicorn'
gem 'sidekiq'
gem 'clockwork'
gem 'sinatra'
gem 'nokogiri'
gem 'date_validator'
gem 'paper_trail'
gem 'paperclip'
gem 'prawn'
gem 'sprockets'
gem 'slim-rails'
gem 'json'
gem 'will_paginate'
gem 'settingslogic'
gem 'state_machine'
gem 'acts-as-taggable-on'
gem 'jquery-rails'
gem 'linguistics'
gem 'i18n'
gem 'sass'
gem 'fb_graph'
gem 'linkedin'
gem 'calendar_date_select'
gem 'refinerycms'
gem 'formtastic'
gem 'datagrid'
gem 'ruport'
gem 'rmagick'
gem 'rqrcode'
gem 'googlecharts'
gem 'prism'
gem 'recaptcha'
gem 'rakismet'
gem 'disqus'
gem 'acts_as_rateable'

is_buntu = `uname -a` =~ /buntu/

group :development do
  gem 'rack-contrib', :require => 'rack/contrib'
  gem 'capistrano'
  gem 'rvm-capistrano'
  gem 'capistrano-ext'
  gem 'thin'
  gem 'rails_view_annotator'
  gem 'mailcatcher'
end

group :development, :test do
  gem 'factory_girl'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'thin'
  gem 'spork-rails'
  gem 'guard'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'guard-livereload'
  gem 'terminal-notifier-guard'
end

group :test do
  gem 'rspec-pride'
  gem 'webmock'
  gem 'vcr'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'launchy'
  gem 'timecop'
  gem 'database_cleaner'
  gem 'simplecov', :require => false
  gem 'headless'
  gem 'json_spec'
  gem 'prickle'
end

