source 'http://rubygems.org'
gem 'mysql2'
gem 'rails', '3.2.6'
gem 'rack'
gem 'chef'
gem 'devise'
gem 'cancan'
gem 'jammit'
gem 'aws-s3', :require => 'aws/s3'
gem 'aws-sdk'
gem 'will_paginate'
gem 'faker'
gem 'omniauth'
gem 'thinking-sphinx'
gem 'unicorn'
gem 'sidekiq'
gem 'clockwork'
gem 'sinatra'
gem 'nokogiri'
gem 'paperclip'
gem 'prawn'
gem 'sprockets'
gem 'slim'
gem 'json'
gem 'transitions', :require => ['transitions', 'active_record/transitions']
gem 'sass'
gem 'settingslogic'
gem 'acts-as-taggable-on'
gem 'jquery-rails'
gem 'linguistics'
gem 'i18n'
gem 'fb_graph'
gem 'linkedin'
gem 'calendar_date_select'
gem 'refinerycms'
gem 'formtastic'
gem 'datagrid'
gem 'ruport'
gem 'rmagick'
gem 'rqrcode'
gem 'googlecharts'
gem 'prism'
gem 'recaptcha'
gem 'rakismet'
gem 'disqus'
gem 'acts_as_rateable'

group :development do
  gem 'rack-contrib', :require => 'rack/contrib'
  gem 'capistrano'
  gem 'rvm-capistrano'
  gem 'capistrano-ext'
  gem 'thin'
  gem 'rails_view_annotator'
  gem 'mailcatcher'
end

group :development, :test do
  gem 'debugger'
  gem 'rspec-rails'
  gem 'thin'
  gem 'spork-rails'
  gem 'guard'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'guard-livereload'
end

group :test do
  gem 'rspec-pride'
  gem 'factory_girl', '~> 2'
  gem 'factory_girl_rails', '~> 1'
  gem 'webmock', '~> 1.8'
  gem 'vcr', '~> 2.1'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'launchy'
  gem 'timecop'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'simplecov', :require => false
  gem 'headless'
end

