require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CirculationsController do

  # This should return the minimal set of attributes required to create a valid
  # Circulation. As you add validations to Circulation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CirculationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all circulations as @circulations" do
      circulation = Circulation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:circulations).should eq([circulation])
    end
  end

  describe "GET show" do
    it "assigns the requested circulation as @circulation" do
      circulation = Circulation.create! valid_attributes
      get :show, {:id => circulation.to_param}, valid_session
      assigns(:circulation).should eq(circulation)
    end
  end

  describe "GET new" do
    it "assigns a new circulation as @circulation" do
      get :new, {}, valid_session
      assigns(:circulation).should be_a_new(Circulation)
    end
  end

  describe "GET edit" do
    it "assigns the requested circulation as @circulation" do
      circulation = Circulation.create! valid_attributes
      get :edit, {:id => circulation.to_param}, valid_session
      assigns(:circulation).should eq(circulation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Circulation" do
        expect {
          post :create, {:circulation => valid_attributes}, valid_session
        }.to change(Circulation, :count).by(1)
      end

      it "assigns a newly created circulation as @circulation" do
        post :create, {:circulation => valid_attributes}, valid_session
        assigns(:circulation).should be_a(Circulation)
        assigns(:circulation).should be_persisted
      end

      it "redirects to the created circulation" do
        post :create, {:circulation => valid_attributes}, valid_session
        response.should redirect_to(Circulation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved circulation as @circulation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Circulation.any_instance.stub(:save).and_return(false)
        post :create, {:circulation => {}}, valid_session
        assigns(:circulation).should be_a_new(Circulation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Circulation.any_instance.stub(:save).and_return(false)
        post :create, {:circulation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested circulation" do
        circulation = Circulation.create! valid_attributes
        # Assuming there are no other circulations in the database, this
        # specifies that the Circulation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Circulation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => circulation.to_param, :circulation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested circulation as @circulation" do
        circulation = Circulation.create! valid_attributes
        put :update, {:id => circulation.to_param, :circulation => valid_attributes}, valid_session
        assigns(:circulation).should eq(circulation)
      end

      it "redirects to the circulation" do
        circulation = Circulation.create! valid_attributes
        put :update, {:id => circulation.to_param, :circulation => valid_attributes}, valid_session
        response.should redirect_to(circulation)
      end
    end

    describe "with invalid params" do
      it "assigns the circulation as @circulation" do
        circulation = Circulation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Circulation.any_instance.stub(:save).and_return(false)
        put :update, {:id => circulation.to_param, :circulation => {}}, valid_session
        assigns(:circulation).should eq(circulation)
      end

      it "re-renders the 'edit' template" do
        circulation = Circulation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Circulation.any_instance.stub(:save).and_return(false)
        put :update, {:id => circulation.to_param, :circulation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested circulation" do
      circulation = Circulation.create! valid_attributes
      expect {
        delete :destroy, {:id => circulation.to_param}, valid_session
      }.to change(Circulation, :count).by(-1)
    end

    it "redirects to the circulations list" do
      circulation = Circulation.create! valid_attributes
      delete :destroy, {:id => circulation.to_param}, valid_session
      response.should redirect_to(circulations_url)
    end
  end

end
